config/routes.rb
Rails.application.routes.draw do
  resources :suscriptors
  get 'home/about'
  get 'home/nacional'
  get 'home/politica'
  get 'home/internacional'
  get 'home/deportes'
  get 'home/farandula'
  get 'home/contacto'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/suscriptor.rb
class Suscriptor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/suscriptors_controller.rb
class SuscriptorsController < ApplicationController
  before_action :set_suscriptor, only: %i[ show edit update destroy ]

  # GET /suscriptors or /suscriptors.json
  def index
    @suscriptors = Suscriptor.all
  end

  # GET /suscriptors/1 or /suscriptors/1.json
  def show
  end

  # GET /suscriptors/new
  def new
    @suscriptor = Suscriptor.new
  end

  # GET /suscriptors/1/edit
  def edit
  end

  # POST /suscriptors or /suscriptors.json
  def create
    @suscriptor = Suscriptor.new(suscriptor_params)

    respond_to do |format|
      if @suscriptor.save
        format.html { redirect_to suscriptor_url(@suscriptor), notice: "Suscriptor was successfully created." }
        format.json { render :show, status: :created, location: @suscriptor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @suscriptor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suscriptors/1 or /suscriptors/1.json
  def update
    respond_to do |format|
      if @suscriptor.update(suscriptor_params)
        format.html { redirect_to suscriptor_url(@suscriptor), notice: "Suscriptor was successfully updated." }
        format.json { render :show, status: :ok, location: @suscriptor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @suscriptor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suscriptors/1 or /suscriptors/1.json
  def destroy
    @suscriptor.destroy

    respond_to do |format|
      format.html { redirect_to suscriptors_url, notice: "Suscriptor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suscriptor
      @suscriptor = Suscriptor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def suscriptor_params
      params.require(:suscriptor).permit(:nombre, :apellido, :correo, :telefono, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/suscriptors_helper.rb
module SuscriptorsHelper
end

app/views/home/_header.html.erb
<nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand"  href="#">TLV Noticias</a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      </li>

        <li class="nav-item">
        <%= link_to "Nosotros", home_about_path, class: "nav-link" %>
        </li>

       <li class="nav-item">
        <%= link_to "Nacional", home_nacional_path, class: "nav-link" %>
      </li>

       <li class="nav-item">
        <%= link_to "Politica", home_politica_path, class: "nav-link" %>
      </li>

        <li class="nav-item">
        <%= link_to "Internacional", home_internacional_path, class: "nav-link" %>
      </li>

        <li class="nav-item">
        <%= link_to "Deportes", home_deportes_path, class: "nav-link" %>
      </li>

        <li class="nav-item">
        <%= link_to "Farándula", home_farandula_path, class: "nav-link"%>
      </li>

   

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Menú
        </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" <%= link_to "Contáctanos", home_contacto_path, class: "nav-link"%> </a>
            
            <a class="dropdown-divider"></a>
            <%=link_to "Suscríbete","http://localhost:3000/suscriptors", class: "dropdown-item"%>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="¿Qué necesitas? " aria-label=" ">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Nosotros</h1>
Resumen

app/views/home/contacto.html.erb
<form>
  <div class="form-group">
    <label for="exampleFormControlInput1">Email</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="nombre@ejemplo.com">
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Motivo de contacto</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>Sugerencias</option>
      <option>Reclamos</option>
      <option>Consultas</option>
    </select>
  </div>
   <div class="form-group">
    <label for="exampleFormControlTextarea1">Escribe</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
</form>

app/views/home/deportes.html.erb
<h1>Deportes</h1>
<h1>La FIFA determina adelantar en un día el inicio del Mundial: la inauguración será con Qatar - Ecuador</h1>

app/views/home/farandula.html.erb
<h1>Farándula</h1>

app/views/home/index.html.erb
<h3>Noticias de último minuto</h3><hr>
<div class="card-group">
  <div class="card">
    <img src="https://www.latercera.com/resizer/6hLUnkRQzRwH7nSFfQWEQf4IdCQ=/768x512/smart/filters:quality(70):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/copesa/PO6NJPM3HBEWBARCSS5KY62Z7E.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Intensas lluvias dejan al menos 28 personas fallecidas en Guatemala</h5>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://www.latercera.com/resizer/L4vr7TOWwqPa2J6eXXcWYaYClvE=/768x512/smart/filters:quality(70):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/copesa/TRSEZZQPR5E3VF47PEMFM6YMHU.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
     <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://www.latercera.com/resizer/gQOdMJIvjKc-lqGDK-5Ao_x6LOw=/768x512/smart/filters:quality(70):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/copesa/4N4SUQ7B5NAVNO4SLL3T3YRETU.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Macron firma el protocolo de ratificación para la adhesión de Suecia y Finlandia a la OTAN</h5>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://www.latercera.com/resizer/0hMvNZDWWBY4W74zTBOkd1BC7GA=/400x267/smart/filters:quality(70):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/copesa/CYFRNCCT5BBTRP2T2KVEAPOLXM.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
     <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://www.latercera.com/resizer/BdXZli9NhCqj0U3drBYZHDG--YM=/400x267/smart/filters:quality(70):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/copesa/3KBKD6Y2AMB4R4NUAWAXWDBRI4.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
       <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
</div>

<hr>

<table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Destacados</th>
                <th>Encabezado</th>
                <th>Cuerpo</th>
                <th>Link</th>
                <th>Fecha</th>             
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Deportes</td>
                <td>La FIFA determina adelantar en un día el inicio del Mundial: la inauguración será con Qatar - Ecuador</td>
                <td>Este jueves, el ente rector del fútbol comunicó la decisión que mover el arranque de la Copa del Mundo al domingo 20 de noviembre. Con ello, será el país organizador el que de el vamos del certamen, como estila la tradición.</td>
                <td><%= link_to "Aquí", home_deportes_path, class: "nav-link"%></td>
                <td>2022-08-11</td>
            </tr>
            <tr>
                <td>Internacional</td>
                <td>El "monstruoso" incendio forestal que está asolando el suroeste de Francia</td>
                <td>Más de 1.000 bomberos luchan contra un incendio forestal "monstruoso" en el suroeste de Francia, que ya ha destruído casi 7.000 hectáreas de bosque, informaron las autoridades.</td>
                <td><%= link_to "Aquí", home_internacional_path, class: "nav-link"%></td>
                <td>2022-08-10</td>
            </tr>
            <tr>
                <td>Nacional</td>
                <td>AChM y autoridades de Transporte se reúnen para abordar plan para el plebiscito del 4 de septiembre</td>
                <td>“Es muy importante planificar y anticipar de manera oportuna un proceso electoral tan importante", señaló la alcaldesa Carolina Leitao. </td>
                 <td><%= link_to "Aquí", home_nacional_path, class: "nav-link"%></td>
                <td>2022-08-10</td>
            </tr>
            <tr>
                <td>Política</td>
                <td>¿Dónde voto? Servel publicará este sábado los puntos y mesas de sufragio, además de la nómina de vocales para el plebiscito</td>
                <td>Con el debut de norma que establece que el local de votación debe ser cercano al domicilio registrado por cada elector, un alto porcentaje de votantes cambiará de local y mesa. Elección del 4 de septiembre es con participación obligatoria.</td>
                <td><%= link_to "Aquí", home_politica_path, class: "nav-link"%></td>
                <td>2022-08-11</td>
            </tr>
          
        </tbody>
       
    </table>

app/views/home/internacional.html.erb
<h1>Internacional</h1>

<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class="active"
          aria-current="true"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item">
          <img
            style="display: block;-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;"
            src="https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1470&amp;q=80"
            width="80%">

          <div class="container">
            <div class="carousel-caption text-start">
              <h1 class="tc">Placa Madre</h1>
              <p class="tc">Placa Madre Gigabyte H410M Intel décima generación m.ATX LGA 1200 Gigabyte</p>
              <p><a class="btn btn-lg btn-primary" href="ventas.html#img_prod_6">Oferta $79.990</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img
            style="display: block;-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;"
            src="https://images.unsplash.com/photo-1583223667854-e0e05b1ad4f3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aHAlMjBub3RlYm9va3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
            width="80%">

          <div class="container">
            <div class="carousel-caption text-start">
              <h1 class="tc">Notebooks HP</h1>
              <p class="tc">Procesador AMD Ryzen™ 5 AMD Radeon™8 GB de RAM DDR4-3200 MHz </p>
              <p><a class="btn btn-lg btn-primary" href="ventas.html#img_prod_4">Oferta $490.990</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item active">
          <img
            style="display: block;-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;"
            src="https://images.unsplash.com/photo-1611241893603-3c359704e0ee?ixlib=rb-.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8c2Ftc3VuZyUyMHRhYmxldHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
            width="80%">

          <div class="container">
            <div class="carousel-caption text-start">
              <h1 class="tc">Tablet Samsung Galaxy Tab A</h1>
              <p class="tc">Sistema Operativo: Android Pie 9,
                Qualcomm SDM429
              </p>
              <p><a class="btn btn-lg btn-primary" href="ventas.html#img_prod_5">Oferta $ 90.990</a></p>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
</div>

app/views/home/nacional.html.erb
<h1>Nacional</h1>

app/views/home/politica.html.erb
<h1>Política</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/carousel/">
>
    <title>Sitio</title>
    

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


  </head>
  <body>
    <%= render 'home/header' %>
    <div class ="container">
      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src=" https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>  
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap4.min.js"></script>
    <script src="..app/javascript/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
    
    <script>
        $(document).ready(function () {
        $('#example').DataTable({
          responsive: true,
          info: false,
          "language" :{
            "search": "Buscar:",
            "lengthMenu": "Mostrar _MENU_"
          }
    })
        });    
    </script>
  </body>
</html>



   
  
    

app/views/suscriptors/_form.html.erb
<%= form_with(model: suscriptor) do |form| %>
  <% if suscriptor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(suscriptor.errors.count, "error") %> prohibited this suscriptor from being saved:</h2>

      <ul>
        <% suscriptor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: inline-block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :apellido, style: "display: inline-block" %>
    <%= form.text_field :apellido %>
  </div>

  <div>
    <%= form.label :correo, style: "display: inline-block" %>
    <%= form.text_field :correo %>
  </div>

  <div>
    <%= form.label :telefono, style: "display: inline-block" %>
    <%= form.text_field :telefono %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: inline-block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/suscriptors/_suscriptor.html.erb
<div id="<%= dom_id suscriptor %>">
  <p>
    <strong>Nombre:</strong>
    <%= suscriptor.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= suscriptor.apellido %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= suscriptor.correo %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= suscriptor.telefono %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= suscriptor.twitter %>
  </p>

</div>

app/views/suscriptors/edit.html.erb
<h1>Editar datos</h1>

<%= render "form", suscriptor: @suscriptor %>

<br>

<div>
  <%= link_to "Ver suscriptor", @suscriptor %> |
  <%= link_to "Volver", suscriptors_path %>
</div>

app/views/suscriptors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Suscriptores</h1>

<div id="suscriptors">
  <% @suscriptors.each do |suscriptor| %>
    <%= render suscriptor %>
    <p>
      <%= link_to "Ver suscriptor", suscriptor %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo suscriptor", new_suscriptor_path %>

app/views/suscriptors/new.html.erb
<h1>Nuevo suscriptor</h1>

<%= render "form", suscriptor: @suscriptor %>

<br>

<div>
  <%= link_to "Volver", suscriptors_path %>
</div>

app/views/suscriptors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @suscriptor %>

<div>
  <%= link_to "Editar datos", edit_suscriptor_path(@suscriptor) %> |
  <%= link_to "Volver", suscriptors_path %>

  <%= button_to "Eliminar", @suscriptor, method: :delete %>
</div>